- uaname: ch.insafety.odoo.app
  name: Odoo Inventory App
- uaname: cn.danatech.xingseus
  name: PictureThis - Plant Identifier
- uaname: cn.wps.moffice_eng
  name: WPS Office-PDF, Word, Sheet
- uaname: mobileoffice
  name: Mobile Office
- uaname: com.connecteamco.connecteam.app
  name: Connecteam Team Management
- uaname: com.connecteam.connecteam
  name: Connecteam Team Management
- uaname: com.btgs.scannerhdlit
  name: Offi Docs